### ISSUE TITLE
Compatibility with multilingual plugins such as WPML and/or Polylang

### ISSUE THREAD

**Issue by cedriccharles4** [10up/distributor#1259]
### Describe your question

Hello there,

First of all, thank you for your plugin that seems to be great!
I have a question: is it compatible with multilingual plugins such as WPML and/or Polylang?

Kind regards,
Cedric

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@cedriccharles4 no, see #332 & #382.

**Comment by willemb2** [comment]
I have tested Distributor with Polylang. Other issues (lack of WEBP support and a bug with inline images) are keeping us from using it on the live sites. But translated posts and pages could be pushed/pulled very well. You will have to push/pull the language versions separately though, since they are separate posts to WordPress. I believe WPML also creates extra posts for each extra language. TranslatePress seems to work completely different.

**Comment by jeffpaul** [comment]
@willemb2 are there specific GH issues for the WEBP and inline images issues you referenced so they can be tracked separately?

**Comment by willemb2** [comment]
@jeffpaul  Yes, #1144 and #810. The issue with inline image URL's: #1262 and possibly #975 and #152 .
