### ISSUE TITLE
Duplication of post meta keys

### ISSUE THREAD

**Issue by arsendovlatyan** [10up/distributor#258]
I was testing Distributor with Woo-commerce (using external connection) and all of the sudden noticed that meta keys getting duplicated in destination, with every update i have more and more duplicated meta keys.

I'm not sure if this is related to 1.3.4 release or #200 , but couldn't find similar bug-report and want to make sure that you are aware about it.

P.C. i have used fresh WordPress install (4.9.8) with fresh WooCommerce (3.5.1) and last version of Distributor 1.3.4

@helen @dkotter want to make sure that you are aware about this issue, we are not using Distributor in production yet, but if other do, it can add a mess in post meta table.

@madmax3365 to follow

**Comment by jakemgold** [comment]
Likely related to 1.3.4 - we tried to handle a situation where the same meta key is used multiple times on the source side (intentionally - WordPress supports that use case)  - and it seems likely that this is unintended side effect with WooCommerce. We'll look into, but in the mean time, you can always roll back to 1.3.3 via Github.

**Comment by helen** [comment]
@arsendovlatyan Looking into this - when you say "with every update", what kind of update are you talking about?

**Comment by jakemgold** [comment]
Quick clarification  - we only see the empty "_test_meta" field being duplicated in your example; all the other fields seem fine. Can you confirm that all or some other fields are also duplicating? Is it just empty key values?

**Comment by helen** [comment]
Commented on the PR about this too but also want to summarize here:

> The only thing that i have noticed, is when you have 2 or more meta values, with the same keys and one of them is empty ('' or 0), in that case, all meta values in distention will eventually be reset to empty.

I think this is the same cause as what I saw in testing #259, which is that all those duplicated meta keys get set to the same value because of the way `update_post_meta()` works (doesn't take an ID). We also don't actually delete any meta at any point, so they just kind of linger there. I think we need to address post meta deletion for sure, but carefully and separately. For now, this is a good enough fix for 1.3.5 and I think will actually also alleviate a back-compat issue I noticed (although I didn't test to make sure it truly works correctly, it just won't fully break).
