### ISSUE TITLE
Using oEmbeds pulls the full markup instead of URLs

### ISSUE THREAD

**Issue by elliott-stocks** [10up/distributor#265]
When pulling in a post that has social URLs (Twitter, Instagram etc) the embed code is pulled instead of the actual URLs. This results in messy HTML on the new post.

Ideally the URLs should be used and the oEmbeds retrieved on the other end, after being pulled.

To replicate -

1. Publish a post with a social URL `https://twitter.com/10up/status/1067517868441387008`
2. Pull in the post on an external site
3. The post content is stored as the following -

```
<div class="oembed-wrapper oembed--twitter">
<blockquote class="twitter-tweet" data-width="500" data-dnt="true">
<p lang="en" dir="ltr">We&#39;re looking for a Creative Director in Seattle, Washington to work closely with clients in the area &amp; others around the world. Come join us!</p>
<p>Role description: <a href="https://t.co/RZ3hPUzeGM">https://t.co/RZ3hPUzeGM</a> <a href="https://t.co/ZNvVNRy6dz">pic.twitter.com/ZNvVNRy6dz</a></p>
<p>&mdash; 10up (@10up) <a href="https://twitter.com/10up/status/1067517868441387008?ref_src=twsrc%5Etfw">November 27, 2018</a></p></blockquote>
<p><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script></div>
```

**Comment by jeremyfelt** [comment]
I just ran into this as well using the internal Network Site Connection with an important addition:

In a multisite configuration, if someone with an editor role adds a YouTube URL to post content and distributes it, the embedded `<iframe>` code applied through `apply_filters( 'the_content' ... )` is stripped out when the post is added on the spoke site because the editor does not have permission to use `<iframe>` as a tag.

When I eliminate `the_content` from the new post arguments (see below), the post content is distributed as expected and the embed works as expected.

https://github.com/10up/distributor/blob/2f93232fb5da171d79c136575f9b854649bb51b5/includes/classes/InternalConnections/NetworkSiteConnection.php#L74

I can use the `dt_push_post_args` filter to overwrite the content myself. This is helpful for the short-term, though running all `the_content` filtering in the first place should be avoidable for performance, IMO.

Along the same lines, if using Gutenberg, Distributor overwrites the `the_content` filtered post content with the original `$post->post_content`. It seems like that decision, along with the decision to use `the_content`, could happen earlier in the process.

**Comment by helen** [comment]
This is my sense of what should probably happen as far as oEmbeds go (not considering the broader sense of when content is/isn't processed at the moment):

* Unhook the `the_content` filter that expands oEmbeds (I believe it's essentially a shortcode, though has some trickery around it)
* Check to make sure the distributed post meta matches up, i.e. avoid external HTTP requests for re-fetching (this would be a huge problem if it happens on viewing the post on the front)
* Update/write tests to account for the new behavior
* Update/write tests to account for what happens when previously distributed posts with oEmbeds are updated

@elliott-stocks @jeremyfelt Thoughts?

**Comment by adamsilverstein** [comment]
Thanks for the detailed bug reports. @elliott-stocks to clarify your sites are not using Gutenberg, correct? Investigating all the scenarios now.

**Comment by elliott-stocks** [comment]
Correct, @adamsilverstein. The sites are not using Gutenberg.
