### ISSUE TITLE
Incompatibility with Ninja Forms: Removes editor styling

### ISSUE THREAD

**Issue by PaddyWhacks** [10up/distributor#287]
Whenever the distributor is activated, it breaks the styling of editor for Ninja Forms. Before and after pictures attached.

![before](https://user-images.githubusercontent.com/9625104/49870291-9a3c1100-fe1b-11e8-9316-1bf050789fa6.png)
![after](https://user-images.githubusercontent.com/9625104/49870292-9ad4a780-fe1b-11e8-8ce0-a5363f37876d.png)

**Comment by robcain** [comment]
Hi,

I have the same issue. Distributor V 1.5.0 stable + Ninja Forms 3.4.24.3 + WP 5.4.2

Distributor plugin, seems to cause Ninja plugin NOT to queue/load some of its admin css - vis:

https://mywebsite.com/wp-content/plugins/ninja-forms/assets/css/normalize.scss
https://mywebsite.com/wp-content/plugins/ninja-forms/assets/css/builder.css?ver=3.4.24.3
.ninja-forms-app #wpcontent * {
	box-sizing: border-box;
}

 - & the absence of these in turn causes breakage described above.

PS: retest with Distributor 1.6.0 - same issue.

A fix for this would be very much appreciated. Thanks.

**Comment by robcain** [comment]
OK. I think I've found the issue: vis: 

file: includes/syndicated-post-ui.php
line: 146
function: add_linked_class

`
...
	if ( 'post.php' !== $pagenow && 'post-new.php' !== $pagenow ) {
		return ''; // Must stick to docblock, cannot return void.
	}
...
`
 - returning empty string here causes the admin body class to be removed (since this is function is added to the 'admin_body_class' filter
 - it seems wp-admin > Ninja Forms > edit form field... -  is meeting this condition ( it also seems very likely that other plugins might equally well do so).

Replacing the above code with:

`
...
	if ( 'post.php' !== $pagenow && 'post-new.php' !== $pagenow ) {
		return $classes;
	}
...
`
 - seems to fix the issue with Ninja Forms.
 - it also seems more logical to return the (filter input) $classes variable, given that is what is returned elsewhere in this function, under (seemingly) similar conditions.

HOWEVER, I have NOT been able to determine what effect this suggested fix is likely to have on the functionality of the distributor plugin itself - there must have been a reason for the original code (and the original code comment  there), unless it was just a mistake - but I'm uncertain.

I wonder if one of the developers could please take a look at this - in particular my suggested fix, to see what (negative)  impact this might actually have.

I desperately need to use this plugin in a new development project and I would very much appreciate some assistance. Many thanks.

**Comment by dinhtungdu** [comment]
@robcain Thank you for the report and research. To me, this is a bug too. Do you want to open a PR to fix this issue?

**Comment by robcain** [comment]
hi @dinhtungdu  Thanks for the response. I agree, it seems better classified as a bug. I'd rather someone else just managed the fix without my further involvement. Many thanks. :)
