### ISSUE TITLE
On Multisite when logged in pages load really slow

### ISSUE THREAD

**Issue by ivanlopez** [10up/distributor#326]
When you have a multisite and you're logged in we've noticed that any page that shows the distributor button in the black bar that page is slow to load. Regardless if you're in the admin or front-end. The more sites you have on your network the slower it gets. When I looked at new relic I noticed that on page load we're sending an HTTP request to each site in order to build out the site list that displays in the distributor menu.

![screen shot 2018-11-26 at 4 09 54 pm](https://user-images.githubusercontent.com/1428016/52492491-50f80b80-2b97-11e9-88f1-4711b74790f4.png)

It looks like is a similar issue to #309

**Comment by jeffpaul** [comment]
Thanks for this @ivanlopez, definitely looks like an opportunity for some performance tweaks.  We'll look into this along with #309 to see what we can improve.  If you have interest and availability to work on a PR, then we'd greatly appreciated... thanks!

**Comment by dkotter** [comment]
@ivanlopez @jeffpaul Made a first pass at some fixes for this issue (see #355). What I was finding, testing this locally, is we currently make HTTP requests to figure out what internal sites a user has access to. This was causing significant slowness on large networks.

The PR mentioned switches that up to use `switch_to_blog` instead of making HTTP requests. Testing this locally with an example site of ~100 connections, I saw page load drop from ~300 seconds to ~6.5 seconds. I've also added caching around these authorized sites, which dropped page load down to about ~5 seconds. Obviously results will vary, based on how many internal connections you have, but should see some decent performance gains.

@ivanlopez If you have time and still have access to the same site to test on, would be great if you could test out the PR and see if that helps with performance issues you were seeing.

There is still more we can do here in regards to performance, though I think this is a good first step. In my opinion, next step would be to refactor the Push UI (and potentially Pull UI), so instead of loading all connection information right away, it only loads when you go to actually push something.

This means for users that are creating posts, editing posts or previewing posts, they won't have the overhead of generating this connection data when they don't actually need it. Thinking something along the lines of when you hover over the Distributor button in the admin bar, we then make a request to get the connection data (could also solve #275 at the same time). Would need some UX discussion to figure out the best way to make it obvious the connection data is loading in but would help overall performance for logged in users editing or viewing content.

There are also some other thoughts I had around performance but would be larger changes/need more discussion. One thing would be to refactor how we handle internal and external connections and merge those together, instead of treating those differently like we do now. Could also look into doing some sort of ajax search interface for Pushing and Pulling, so we would never grab all connections, that data is only fetched as you search. I personally don't love those sort of search interfaces, as you have to know what you're searching for in order to easily find it, but would help even more with performance, as we would never grab all connections and never grab connections that aren't needed, only the ones searched for.

**Comment by jeffpaul** [comment]
@ivanlopez any updates on being able to test PR #355 to see how it improves/impacts your loading issue?
