### ISSUE TITLE
Submit package to Packagist

### ISSUE THREAD

**Issue by vburlak** [10up/distributor#356]
Hey guys,
I just tried to install this awesome plugin in my Bedrock instance and found that it isn't available to Install via Composer:
~~Running `composer require 10up/post-finder`, but with no luck.~~
Running `composer require 10up/distributor`, but with no luck.

It seems that plugin not registered in Packagist [https://packagist.org/packages/10up/](https://packagist.org/packages/10up/)

I've checked plugin's `composer.json` and everything is fine and plugin is completely ready to be [submitted to Packagist](https://packagist.org/packages/submit)!

I've tried to submit package to Packagist, but got
> The vendor is already taken by someone else. You may ask them to add your package and give you maintainership access. If they add you as a maintainer on any package in that vendor namespace, you will then be able to add new packages in that namespace. The packages already in that vendor namespace can be found at [10up](https://packagist.org/packages/10up/)

So, It will be great, if somebody who maintain this package will do a just few click on Packagist website and submit this plugin here https://packagist.org/packages/10up/ to be available to Install via Composer.

Thanks!

**Comment by jeffpaul** [comment]
@vburlak your comment references `10up/post-finder`, but this is the `10up/distributor` repo.  If your question is in relation to Post Finder, then let's move this issue to the [10up/post-finder repo](https://github.com/10up/post-finder).  Otherwise, please clarify that you meant to reference `10up/distributor`... thanks!

**Comment by vburlak** [comment]
Hey @jeffpaul 
Oh, here is a typo in my reference, my question is related to `10up/distributor` repo.
Actually, needs to be used `composer require 10up/distributor`
Thanks!

**Comment by matgargano** [comment]
any update here? seems this would be a simple task

**Comment by helen** [comment]
Right now Distributor asks for a (free) registration key for continued updates as a part of some goals that 10up has around user engagement and the feedback loop, we are discussing how this does or doesn't align with that and how it might impact client usage/updates as well, since we use Distributor ourselves :)

**Comment by helen** [comment]
Serendipitous timing - managed to have a group conversation about this today. For the moment, we are not going to put this on Packagist as it runs counter to having the registration key/user feedback loop component that is an important part of keeping this significant work free and open source. I promise I am not ignoring the base of the request - we use Composer to pull in plugins on many projects as well. It's just not what makes sense for Distributor right now.

**Comment by vburlak** [comment]
Thanks for the response @helen. It makes sense
