### ISSUE TITLE
Apply hook in the `meta_box_external_connection_details(..)` function

### ISSUE THREAD

**Issue by avag-novembit** [10up/distributor#383]
In order to add ability to add 'external connection details' outside the plug-in going to create a pull request, which appends `do_action( 'dt_meta_box_external_connection_details', $post );` in the `meta_box_external_connection_details(..)` function.

**Comment by jeffpaul** [comment]
@avag-novembit thanks for the heads up, looking forward to the PR for the team to review!

**Comment by helen** [comment]
Hi @avag-novembit - thanks for taking the time to contribute back with hooks you've needed as you do extensive things with Distributor. We're preparing to get a 1.5 release out with some significant performance enhancements and a couple of bug fixes, and have decided to leave out additional hooks for now so we can holistically review them to make sure they won't end up broken in the near future as Distributor continues to evolve.

For this hook, I think we need to consider the placement as well as the surrounding HTML structure and how much a developer needs to know and recreate in order to keep consistent with the rest of the screen. An open hook like that allows for a lot of flexibility but also means a lot of maintenance on your end to make updates if/when Distributor changes.

**Comment by avag-novembit** [comment]
Hi @helen, okay, thanks for the comment.

**Comment by jeffpaul** [comment]
Tagging @arsendovlatyan on this per their request.

**Comment by jeffpaul** [comment]
This has been hanging around for quite some time and is still just a bit too broad in what it would allow / pressure it would put on any extensions to adjust with every Distributor update.  As such I'm going to close this out as not desirable to add into Distributor at this time.
