### ISSUE TITLE
Add hook to modify connection cpt arguments

### ISSUE THREAD

**Issue by avag-novembit** [10up/distributor#394]
Created another PR to add `dt_before_setup_cpt` filter to make possible to modify `dt_ext_connection` custom post type arguments.

**Comment by jeffpaul** [comment]
@avag-novembit thanks again for the heads up and for the related PR for the team to review, your contributions are much appreciated!

**Comment by adamsilverstein** [comment]
@avag-novembit thanks for your contribution here - can you explain briefly the use case for this filter and point me to previous tickets I may have missed?

**Comment by avag-novembit** [comment]
I don't think there is a ticket for it. It allows to modify registered `dt_ext_connection`  custom post type arguments, particularly, (in our case) to add `taxonomies` to cpt arguments. Which, in its turn, needed for "connection groups" functionality, which will be a separate add-on.

**Comment by adamsilverstein** [comment]
@avag-novembit You can use the existing core `register_post_type_args` filter to alter the args used to set up the CPT (see https://developer.wordpress.org/reference/hooks/register_post_type_args/). With this filter you can catch the post type being registered, then modify or add your own args.  

Does that make sense, or is there something this would not enable for your use case?

Because this is something you can already achieve with existing filters, I'm inclined to close this issue. Please let me know if I am missing something.

**Comment by jeffpaul** [comment]
Closing in favor of using the `register_post_type_args` filter.
