### ISSUE TITLE
No Push option

### ISSUE THREAD

**Issue by noponid** [10up/distributor#605]
**Describe your question**

I have 2 new WP installations running locally (localhost/wp1 and localhost/wp2) for testing purposes. Plugin is installed on both sites and i have set up External Connection from WP1-WP2. Got the green light and it works, i can pull sample post from WP2 to WP1.

But, when i go and write a post on WP1 i dont see any option to push it to WP2... On your site i see how it should look (black box above the post area) but it doesnt show on my end... Is this feature only available on sites in multisite network?

Any help would mean a lot :)

**Comment by jeffpaul** [comment]
@noponid welcome to Distributor!  If you're using Gutenberg for editing, you will need to disable its fullscreen mode in order to see the admin bar.  If you're not seeing Distributor in the admin bar, then it may require a page refresh within Gutenberg.  If you're still not seeing Distributor in the admin bar after publishing a post, then please share more details about your environment so I can help further triage for you... thanks!

**Comment by noponid** [comment]
Hey Jeff, thanks a bunch for quick reply!
Yep, Gutenberg was the issue... I could swear i disabled fullscreen but i havent... Sorry and thanks again :)

**Comment by jeffpaul** [comment]
@noponid glad that solved it!  I'm going to close this issue, but please come back this way if you've run into any other issues / questions / ideas on how to improve Distributor to better meet your needs... thanks!
