### ISSUE TITLE
Taxonomy terms don’t sync among sites.

### ISSUE THREAD

**Issue by manolobevia** [10up/distributor#625]
Let’s say I have 2 sites (Site A and B). I create several posts with taxonomy terms on B, then in site A I pulled from B, and I am able to see the posts pulled form B with their taxonomy terms.
Then I update a post on site B with it has 3 taxonomy terms, but I decide to delete one.
Site A is synced with B, and the post is updated showing two taxonomy terms. If I add more terms on B, A is synced too. If I delete others on B, but at least I leave one term, site A is synced too. The problem is if I delete all the terms on B, site A doesn’t sync.

Is there a way to solve this situation with taxonomy terms?

**Comment by jeffpaul** [comment]
@manolobevia I ran through some tests on this, specifically the point where this breaks for you (`The problem is if I delete all the terms on B, site A doesn’t sync.`) and if I remove all terms in Gutenberg or Classic Editor the changes sync as expected.  However, using Quick Edit from the All Posts screen to remove all terms I do see that the terms removal does NOT sync as expected but ONLY from posts created in Gutenberg but not ones from Classic Editor.

Note that I'm going to milestone this for our 2.0 release as it aligns with some of the planned work on making push/pull operate more similarly code-wise.

**Comment by manolobevia** [comment]
@jeffpaul thank you!!!!

**Comment by peterwilsoncc** [comment]
I was testing this and able to reproduce the issue when deleting all tags and updating via the REST API. 

My suspicion is that it has something to do with an `empty( $terms )` check but I am doing some further checking to see whether it's an issue with the plugin or the REST API.
