### ISSUE TITLE
Updating original breaks parent-page of distributed content

### ISSUE THREAD

**Issue by andrewortolano** [10up/distributor#655]
Steps to reproduce:

1. Create a page in Site A of a Wordpress Multisite
2. Distribute it to Site B of the same Wordpress Multisite
3. In Site B, give that page a parent
4. In Site A, make a text edit to the page
5. In Site B, the page will have moved back to the root, and no longer have its assigned parent.

**Comment by jeffpaul** [comment]
@andrewortolano welcome to Distributor and thanks for the feedback!  In general distributed content is blocked from being updated in order to maintain the content sync, so it's likely that we may want to limit the ability to assign a parent page to distributed pages though we'll need to test and see what should be the expected result.  Suffice to say, you'd like to be able to update the parent page assignments while maintaining the content sync?

**Comment by andrewortolano** [comment]
> you'd like to be able to update the parent page assignments while maintaining the content sync

Yes! Here's our use case:

We're developing a WP network for a college and its departments. 

- You can go to college.edu/majors/chemistry to read about the Chem Major. 
- The Chem Major page was distributed to chemdepartment.college.edu/chemistry
- It was then given the parent, "majors"
- Distributed content took the permalink: chemdepartment.college.edu/majors/chemistry
- But then updating the content of the original moved the distributed back to the root of its site

**Comment by motolano** [comment]
Hey, @jeffpaul ,

I'm providing this snippet because it's not entirely clear to me if the changes I'm asking for would be considered desirable changes to the software. However, if anyone wants to use my filter:

/**
 * When pushing posts, don't change the destination post date or destination parent:
 */
function filter_dt_push_post( $post_body ) {
  if ( isset( $post_body['ID'] ) ) {
    $existing_date = date( 'Y-m-d H:i:s', get_post_time( 'U', false, (int) $post_body['ID'] ) );
    $post_body['post_date'] = $existing_date;
    $distributed_post_post_parent = wp_get_post_parent_id($post_body['ID']);
    $post_body['post_parent'] = $distributed_post_post_parent;
  }
  return $post_body;
}
add_filter( 'dt_push_post_args', __NAMESPACE__ . '\filter_dt_push_post', 10 );

**Comment by andrewortolano** [comment]
Hey, @jeffpaul ,

I'm providing this snippet because it's not entirely clear to me if the changes I'm asking for would be considered desirable changes to the software. However, if anyone wants to use my filter:


/**
     * When pushing posts, don't change the destination post date or destination parent:
 */
`function filter_dt_push_post( $post_body ) {`
`  if ( isset( $post_body['ID'] ) ) {`
`    $existing_date = date( 'Y-m-d H:i:s', get_post_time( 'U', false, (int) $post_body['ID'] ) );`
`    $post_body['post_date'] = $existing_date;`
`    $distributed_post_post_parent = wp_get_post_parent_id($post_body['ID']);`
`    $post_body['post_parent'] = $distributed_post_post_parent;`
`  }`
`  return $post_body;`
`}`
`add_filter( 'dt_push_post_args', __NAMESPACE__ . '\filter_dt_push_post', 10 );`

**Comment by ramen-drama** [comment]
Thanks @andrewortolano This was a lifesaver! I feel like pushing as orphan makes sense but vote that maintaining parent designations on remote should be standard or a setting option.

**Comment by peterwilsoncc** [comment]
It looks like this was resolved during the 2.0.0 release cycle when Distributor switched to using `wp_update_post` for updating distributed content. If the parent is not set, pages use the existing value.

As the parent post is not set when a post is pushed or pulled (as the ID may or may not exist), I think it's good to allow the parent to be modified on the remote site. To wrap this up, I'd suggest making sure the parent can be set on distributed content in all circumstances:

* quick edit (currently the case)
* block editor (currently unable to change)
* classic editor (currently unable to change)
