### ISSUE TITLE
Video Gutenberg Blocks are stripped partially. Video's after push don't work

### ISSUE THREAD

**Issue by Pitemedia** [10up/distributor#684]
**Describe the bug**
After a push the video Gutenberg blocks are only partially copied to the new site. There are some key elements being stripped:

wp:core-embed/youtube {"url":"https://youtu.be/WNRBqGcVbX0","type":"video","providerNameSlug":"youtube","className":"wp-embed-aspect-16-9 wp-has-aspect-ratio"}

This is the only part being copied: 
figure class="wp-block-embed-youtube wp-block-embed is-type-video is-provider-youtube wp-embed-aspect-16-9 wp-has-aspect-ratio"><div class="wp-block-embed__wrapper"
https://youtu.be/WNRBqGcVbX0
/div/figure
End of only part being copied

 /wp:core-embed/youtube

**Comment by jeffpaul** [comment]
@Pitemedia welcome to Distributor and thanks for the feedback.  Can you confirm some of the details from your Site Health Info export or general WP/plugins/themes info as noted in the bug report template to help us try to replicate your issue?
```
- WordPress version: <!-- [e.g., 5.3.2] -->
 <!-- If your WordPress version is below 5.2, then please fill out the Plugins and Themes items below. -->
 - Plugins and version: <!-- [e.g. PluginA 1.0.0, PluginB 2.1.0, PluginC 3.2.1] -->
 - Theme and version: <!-- [e.g. Twenty Nineteen 1.3] -->
 <!-- If your WordPress version is 5.2 or higher, then please fill out the Site Health Info details below. -->
 - <details><summary>Site Health Info:</summary>
   <!-- Go to Tools > Site Health > Info tab, click "Copy site info to clipboard", and paste those details here. -->
   </details>
```

**Comment by dkotter** [comment]
@Pitemedia I just tested pushing a post with a YouTube embed block in it to both an internal connection and an external connection, running Distributor 1.6.2 and WordPress 5.6.1 and everything distributed as I would expect it.

From the HTML you pasted, it does seem similar to other issues we've seen in the past around distributing Gutenberg content. Basically we've had issues where sometimes Distributor doesn't properly recognize that both sites are using Gutenberg and so it tries to distribute rendered content, instead of the raw content, which will contain the block markup. This could result in some markup being removed that would break things.

That said, we've put multiple fixes in place to help with this issue, so would be helpful to know what version of Distributor you are running, what WordPress version you're running and if you're using Gutenberg on both sites (the origin site and the site you are distributing to). Thanks!

**Comment by jeffpaul** [comment]
@Pitemedia can you please provide additional details on your setup so we can help further triage this for you?

**Comment by jeffpaul** [comment]
@Pitemedia can you please provide additional details on your setup so we can help further triage this for you?
