### ISSUE TITLE
Pulled/Pushed posts grab incorrect images

### ISSUE THREAD

**Issue by rchalhoub** [10up/distributor#714]
**Describe the bug**

Hello, we are using Distributor 1.6.2, network activated on our multisite.  We are running multiple real estate sites and want to be able to push/pull property listings between them.  When we attempt this, the featured image is copied over correctly, as is the text content, categories, etc. But the gallery images aren't moving over correctly, the plugin picks random images to fill the spots.

All the images are jpegs.

In the Distributor settings we have it set to process featured images as well as attached images.

Here's an example of one of the sites: https://homes.sc/

**Additional site info:**
• Wordpress 5.6.1
• Theme: Real Places

**Plugins:**
Google Analytics
HugeIT Forms
Inspiry Real Estate
List Custom Taxonomy Widget
Mortgage Calculator
Post Types Order
Random Banners
Redirection
Responsive Mortgage Calculator
Simple Share Buttons Adder
WordPress Importer
WPBakery Page Builder
Yoast SEO

**Comment by dkotter** [comment]
@rchalhoub Thanks for the report!

This sounds similar to #486 (and a few others as well). This is a known issue with Distributor (somewhat documented here: https://github.com/10up/distributor#known-caveatsissues) where if you have it set to bring over all attached images, the images themselves should be transferred to the receiving site but the plugin does not do any sort of search/replace on those images or their IDs.

For example, I'm not exactly sure how you're building the image galleries but a common approach for those is you choose the images you want displayed in the gallery and then the actual image IDs are stored, in order to render those gallery images out. So in this case, the images themselves may be transferred when Distributing but the referenced image IDs are left alone, instead of getting replaced to point to the newly transferred images.

This results in what you're seeing, where seemingly random images show up. Basically if there are images on the receiving site that have the same ID's, those are what will show. It's probably unlikely that all the image IDs will match, so you'll probably also end up with some blank/broken images in the gallery.

There are ways you can customize the distribution behavior to account for this on your end (some details here: https://github.com/10up/distributor#known-caveatsissues) but this is on our list to find a good solution for. The tricky part is determining when things should be replaced, whether those are image URLs or image IDs, as there will be some scenarios where those shouldn't get updated and others that will need it.

**Comment by andrewhenning** [comment]
Hi all - Love the plug-in but have the same issue that image fields beyond the featured image created in ACF don't link.  They pull through to the media library but aren't visible for the editor or selecting in a template through meta-data.  (I am using Oxygen).   Any help on how you might customise the code to reference them appreciated.   Or...  when might the Distributor 2 be released?

**Comment by jeffpaul** [comment]
@andrewhenning there's a broad issue with how ACF and page builders (like Oxygen) store their data that doesn't currently play well with Distributor.  We're planning to tackle a part of this issue with the 2.0.0 release (likely later this year), but the broader compatibility testing and resolution for various 3rd party plugins (like ACF and page builders) isn't planned until 2.1.0 which may not happen until 2022.  If this is a more urgent/important issue for you, email me (jeff.paul@10up.com) and we can discuss alternate options.

**Comment by jeffpaul** [comment]
Closing in favor of #445, please subscribe to that issue for future updates on our progress.
