### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Drmzindec** [10up/distributor#773]
When a site isnt a multi site and you want to edit an imported article it does a check in the below file and gets a Fatal error.

```
Fatal error: Uncaught Error: Call to undefined function Distributor\SyndicatedPostUI\switch_to_blog()
in /home/ubuntu/test/wp-content/plugins/distributor-develop/includes/syndicated-post-ui.php on line 541
Call stack:
    Distributor\S\enqueue_gutenberg_edit_scripts()
    wp-includes/class-wp-hook.php:292
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:316
    WP_Hook::do_action()
    wp-includes/plugin.php:484
    do_action()
    wp-admin/edit-form-blocks.php:409
    require()
    wp-admin/post.php:187
```

**Comment by jeffpaul** [comment]
@Drmzindec looking at the file location for the plugin files it looks like you may have downloaded a ZIP of the `develop` branch for your use.  If that's the case, you're better off using the built version from the `stable` branch or the ZIP file referenced on a [specific release](https://github.com/10up/distributor/releases).

**Comment by Drmzindec** [comment]
@jeffpaul I have used the latest stable branch and the error is the same:

```
Fatal error: Uncaught Error: Call to undefined function Distributor\SyndicatedPostUI\switch_to_blog()
in /home/ubuntu/test/wp-content/plugins/distributor-1.6.4/includes/syndicated-post-ui.php on line 541

Call stack:

    Distributor\S\enqueue_gutenberg_edit_scripts()
    wp-includes/class-wp-hook.php:292
    WP_Hook::apply_filters()
    wp-includes/class-wp-hook.php:316
    WP_Hook::do_action()
    wp-includes/plugin.php:484
    do_action()
    wp-admin/edit-form-blocks.php:409
    require()
    wp-admin/post.php:187
```

The lines in the file:

```
switch_to_blog( $original_blog_id );
$original_location_name = get_bloginfo( 'name' );
restore_current_blog();
```

The site i am running this on is not a multisite so the above line that produces the fatal error will never be able to run successfully.

However something like the below will solve the issue:

```
if (is_multisite()) {
    switch_to_blog($original_blog_id);
    $original_location_name = get_bloginfo('name');
    restore_current_blog();
}
```

**Comment by dkotter** [comment]
@Drmzindec Thanks for the detailed report.

I tried to reproduce myself in a brand-new single site install and did not encounter the same problem.

Looking at the lines in question, the call to `switch_to_blog` only happens if we have a value in `$original_blog_id`, which comes from the post meta key of `dt_original_blog_id`. In theory, that key should only be set if you are dealing with an item that was imported from an internal connection, which internal connections are only at play within a WordPress multisite.

I'm wondering if you could provide more information on your set up? For the item you are editing (and seeing this error) did that come from Distributor? If so, was that a push or a pull? And what type of connection did you use for that? I could also see an issue here if you were previously on a multisite but you convert that to a single site (or extract a site out of multisite into it's own stand-alone site). We can definitely add `is_multisite` checks where needed but in theory, the checks we have should work in a standard set up.

**Comment by Drmzindec** [comment]
@dkotter Thank you for the response. 

We had a site that was a multisite of 8 sites, and we split that into 8 individual sites as it was getting too big to maintain on the multisite setup. But we kept the distributor plugin since we still wanted to share posts across the sites.

- Yes we used the paid version of Distributor.
- The post in question was a push as far as I am aware, (Editorial team is offline today, but can confirm if needs be).
- The post came from an external connection.

When converting the sites to stand alone sites, we didnt flush the meta fields since there was a lot of legacy data that we wanted to keep in the event that the editorial team might have a need for it again (Which has happened), which in this case could be the issue since they Distribute older posts at times as well.

In theory if i run a script to clean up the meta field `dt_original_blog_id` it should resolve the issue then? Ideally I think going with a check `is_multisite` from your side might be better in the long run since not all users and not all devs will do a check to resolve this and having that redundancy might save users some time?

**Comment by Drmzindec** [comment]
I ran `DELETE FROM wp_postmeta WHERE meta_key = 'dt_original_blog_id';` which seems to have solved the problem. I still think it would be a good idea to add the check in there for people who arent aware of this.

@dkotter thanks for pointing me in the right direction.
