### ISSUE TITLE
Media not transferred.

### ISSUE THREAD

**Issue by uttam-49** [10up/distributor#786]
I am using a distributor to clone pages into my other site. I have a page builder elementor used with ACF meta fields. Everything works fine except the media images. Feature image is being transferred and added into the other media library too but images used in elementor modules and ACF modules were not copied. So anyone has any solution for this then please help me.

**Comment by jeffpaul** [comment]
@uttam-49 note that this is a known issue and currently tracked via #81 so please subscribe to that issue for updates.  Note that the issue is milestoned for a release a bit off in the future, so if this is of an urgent or important nature for you then please reach out to me directly (jeff.paul@10up.com) and we can discuss alternate options... thanks!
