### ISSUE TITLE
Uncaught TypeError: can't access property "innerText", T is null

### ISSUE THREAD

**Issue by Drmzindec** [10up/distributor#795]
Ive had this issue on some of my sites recently, the plugin was working fine without any issues and still is on some 7/8 of my sites.

`Uncaught TypeError: can't access property "innerText", T is null - push.js:127:2`

This happens on version 1.6.4 and 1.6.5 when distributing from the front end.

**Comment by dkotter** [comment]
@Drmzindec Thanks for the report! I was able to reproduce this console error and is an issue with a missing element that we expect to be in place, that is used to render any error messages. This will be fixed by #803.

Note though that this won't fix any issues you may be running into when pushing content. It will address the console error you are seeing and should provide you with a better error message when something goes wrong. Hopefully that error message will help diagnose what is actually going wrong.
