### ISSUE TITLE
Previously pulled posts appear in new tab

### ISSUE THREAD

**Issue by jeffpaul** [10up/distributor#808]
**Describe the bug**
When having two separate WP instances connected via an External Connection and using the Pull Content screen, previously pulled posts appear in the New tab view.  Note that in the case that was demo'd to me that the Bulk Pull option was used and not individual post pull actions.

**Steps to Reproduce**

**Expected behavior**
Previously pulled posts should only show in the Pulled tab view and not in the New tab view.

**Screenshots**

<img width="1205" alt="Screen Shot 2021-10-13 at 9 33 19 AM" src="https://user-images.githubusercontent.com/2818133/137154694-ee09e64e-54ed-41ff-84f9-bfa17deadec3.png">

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - WordPress version: 
 
 - Plugins and version: 
 - Theme and version: 
 
 - <details><summary>Site Health Info:</summary>
   
   </details>

**Additional context**

**Comment by dkotter** [comment]
This is similar to the issue reported in #809. The issue can be found here: https://github.com/10up/distributor/blob/develop/includes/classes/PullListTable.php#L487

Basically we grab all skipped and previously pulled items and then trim that down to only 200. Those are then excluded from our queries. But if you have more than 200 items pulled, you could then start seeing previously pulled items (or skipped items) in the New tab. This impacts both internal and external connections the same.

I think the same solution we land on for #809 will solve this one as well (or vice versa if you want to look at it that way). Basically we need to ensure all pulled and skipped items get excluded, not just the latest 200, and do it in a way that doesn't impact performance.

**Comment by cadic** [comment]
I suppose the threshold of 200 items was added to meet the URL limit while performing GET requests for external connections. We could not bypass that using POST method because `POST /wp/v2/posts` is to create post.

Maybe we could change the way how we retrieve posts. Skip `exclude` argument from the remote request, increase `posts_per_page` by `count( (array) $ignored_post_ids )` and fake the pagination using calculated `offset` instead of `page`. Later we could filter out unwanted posts from the response.

But this will bring another problem with huge bandwidth if the site already has lot of skipped/pulled items. And also it will take longer to the remote site to generate REST response.
