### ISSUE TITLE
Document or remove `-dev` from the PHP version number

### ISSUE THREAD

**Issue by helen** [10up/distributor#820]
**Is your enhancement related to a problem? Please describe.**
The `-dev` suffix has proven to be a little confusing at release time and may not even be necessary now. We should evaluate and then, if it is necessary, document it in code and documentation better. My recollection is that it was added primarily to be able to warn users that they're running a development version and need to run the build from time to time. We could probably achieve the same result but checking if one of the dev version files exists instead.

**Describe the solution you'd like**
A less-confusing release process.

**Designs**
n/a

**Describe alternatives you've considered**
Leaving it alone

**Additional context**

**Comment by jeffpaul** [comment]
@dkotter I'm generally fine leaving the `-dev` version flag as the last step in the release process, but open to alternate ways to throw an admin notice when using Distributor via `develop` instead of a proper released version.  What's your thought on best / realistic approach on this?

**Comment by dkotter** [comment]
I think this issue was opened up by Helen initially because I was confused by that `-dev` flag and how it was handled during releases. I'm up to speed on it now so it's not an issue for me but thinking of the future where other's may be handling releases, I do think it's worth deciding how to approach this.

From what I'm seeing in the code, we only use this flag to output an admin notice, nothing else. If that's the case, my suggestion is to remove that flag and as Helen mentions, use something else to determine when that notice should be shown. This probably is just a check for one of our development only files (like `composer.lock` or `webpack.config`)

**Comment by jeffpaul** [comment]
Yeah `composer.lock` seems reasonable, even if perhaps that doesn't capture ALL scenarios that should suffice for the need of showing the admin notice and to remove that manual step in the release process.
