### ISSUE TITLE
Cannot Delete Distributed Posts

### ISSUE THREAD

**Issue by LucyTurtle** [10up/distributor#821]
**Describe the bug**
When trying to delete a post that has been distributed to other sites it errors out. I have tried from the "posts" page, and the post editing page. I tried deleting distributed versions first.

**Steps to Reproduce**
Try to delete a distributed post

**Expected behavior**
The post would delete

**Screenshots**
Fatal error: Uncaught TypeError: Argument 1 passed to Distributor\InternalConnections\NetworkSiteConnection::__construct() must be an instance of WP_Site, null given, called in /www/searchsites_680/public/wp-content/plugins/distributor-stable/includes/classes/InternalConnections/NetworkSiteConnection.php on line 640 and defined in /www/searchsites_680/public/wp-content/plugins/distributor-stable/includes/classes/InternalConnections/NetworkSiteConnection.php:53 Stack trace: #0 /www/searchsites_680/public/wp-content/plugins/distributor-stable/includes/classes/InternalConnections/NetworkSiteConnection.php(640): Distributor\InternalConnections\NetworkSiteConnection->__construct(NULL) #1 /www/searchsites_680/public/wp-includes/class-wp-hook.php(303): Distributor\InternalConnections\NetworkSiteConnection::separate_syndicated_on_delete(559) #2 /www/searchsites_680/public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) #3 /www/searchsites_680/public/wp-includes/plugin.php(470): WP_Hook->do_action(Array) #4 in /www/searchsites_680/public/wp-content/plugins/distributor-stable/includes/classes/InternalConnections/NetworkSiteConnection.php on line 53

**Comment by jeffpaul** [comment]
@LucyTurtle can you confirm your WordPress and Distributor versions as well as the active theme and any other relevant active plugins?  Also confirmation if this is a network set up or separate WordPress installs will help us to replicate your setup / better triage your issue... thanks!

**Comment by LucyTurtle** [comment]
Hodwy there! I am on a multi-site setup. Wordpress version 5.8.2, Distributor version 1.6.7. 
Theme: GeneratePressVersion: 3.1.0
Plugins: 
- Distributor Version 1.6.7
- GP Premium Version 2.1.1
- Imagify Version 1.10
- Relevanssi 4.14.4

We have been using your plugin for quite a while (since maybe around May?)  but I am unsure when this issue started. I don't think until now I had to delete a post on the master site we use for distributing. Thanks for your help!

**Comment by dkotter** [comment]
Thanks for the report @LucyTurtle. I was not able to reproduce the issue myself but looking at the original error message you provided, I do think there's a scenario that could cause problems. Not sure if this is what you might have experienced but right now if you:

1. Distribute an item to a site
2. Then at some point delete that site
3. And then go back and try and delete the original item, you'll end up with the error you see because we are trying to access a site that no longer exists

I would guess this is closer to an edge case situation but still something we should account for. I've opened #830 that adds better checking to ensure we have proper data before proceeding that I believe should solve this.

**Comment by LucyTurtle** [comment]
Hi there! This has got to be it! We are constantly adding and removing websites. So it makes sense!
