### ISSUE TITLE
[Security] Workflow build-docs.yml is using vulnerable action actions/checkout

### ISSUE THREAD

**Issue by qazaqstan2025** [10up/distributor#827]
The workflow build-docs.yml is referencing action actions/checkout using references v1. However this reference is missing the commit [a6747255bd19d7a757dbdda8c654a9f84db19839](https://github.com/actions/checkout/commits/a6747255bd19d7a757dbdda8c654a9f84db19839) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by jeffpaul** [comment]
@qazaqstan2025 thanks for the heads up on this!  I'm noting for our team that there are a couple places that we'll want to look in updating things released to `actions/checkout@v1`: https://github.com/search?q=org%3A10up+%22actions%2Fcheckout%40v1%22&type=Code.  I'm pinging our Open Source Practice team (@10up/open-source-practice)so that one of them can look to craft PRs for each of the `actions/checkout@v1` references, validate that impacted GitHub Actions still work as necessary, and then coordinate merging/releasing.
