### ISSUE TITLE
Could not determine remote post id

### ISSUE THREAD

**Issue by vlastaw** [10up/distributor#847]
Attempt to push Post (not as draft) results in "Could not determine remote post id" error message, post is not pushed.

As we only use Distributor once in a couple of weeks, I don't know what changes on either end might have caused this (pushing worked before). Updated Distributor to 1.6.8 on both ends, error still present. Source WP is 5.8.2, target was 5.7.5 upgraded to 5.9 with no change to this behavior.

I may be helpful in tracing the cause of the error if you please explain to me to what exactly does distributor respond with it (because pushing creates the remote post, I don't know, why shouldn't it be able to determine its id).

Nothing in debug.log nor PHP err log.

Thank you!

**Comment by dkotter** [comment]
@vlastaw Thanks for the report. In looking through our codebase, I only ever see that error message being used when pushing content to an external connection though you mention you're trying to pull? Can you verify that for me? And you mention the source and target sites. Are you trying to pull content from the target site into the source site? Or push content from the source site to the target site? Or some other combination?

**Comment by vlastaw** [comment]
@dkotter First I wrote pull in my post, but edited that in minutes and now it's push for four days :) I am trying to PUSH a post from SOURCE site (the one I admin and am logged to) to a remote TARGET site. Thank you!

**Comment by dkotter** [comment]
At a high level, here's what happens when an item is pushed to a remote site:

1. We make a GET request to the `types` endpoint (https://example.com/wp-json/wp/v2/types) to determine the correct REST API endpoint we need to use to create an item. We take the result of that request and we look for a matching post type and then within that, find the `_links` > `wp:items` > `href` item. This will be the endpoint we use to create an item
2. Assuming this finds a correct endpoint match, we then build up the data we want to send and then make a POST request to that discovered endpoint. If you are pushing a post, this endpoint should look like https://example.com/wp-json/wp/v2/posts
3. We check the response of this request to ensure it's not an error and we also check to ensure the response body contains an `id` parameter. If this doesn't exist, we then return the error message you are seeing

The only scenario this should happen is if the `wp_insert_post` call on the remote/target site didn't work. That function, if it fails, will either return a `WP_Error` object or zero. If it was returning a `WP_Error` object, the error message you are seeing would be different, so it's almost certainly returning zero. There's multiple scenarios where it might return zero but hard to say what is happening in your case without additional details. If you haven't already, I'd suggest turning on debugging on your TARGET site and seeing if anything shows in the logs of that environment (not the SOURCE site).

**Comment by vlastaw** [comment]
OK, will try and get back. Thank you very much!

**Comment by vlastaw** [comment]
Hallo Darin, unfortunately nothing regarding Distributor in Debug.log on neither server.

BUT! We found ONE post, which can be distributed. However, we are not able to replicate why (replication of any of its properties on another post did not lead to success).

What now? :-( Thank you.

**Comment by michalletavka** [comment]
I managed to replicate the issue trying to push from some other website to the same website @vlastaw is pushing to.

I put debug prints into includes/classes/ExternalConnections/WordPressExternalConnection.php
```
if ( empty( $body_array['id'] ) ) {
    error_log(print_r($body, true));
    error_log(print_r($body_array, true));
    error_log(print_r($body_array['id'], true));
    return new \WP_Error( 'no-push-post-remote-id', esc_html__( 'Could not determine remote post id.', 'distributor' ) );
}
```

Trying to push a post again results in following debug prints:

```
[01-Mar-2022 00:40:00 UTC] <br />
<b>Warning</b>:  call_user_func_array() expects parameter 1 to be a valid callback, function '_disable_block_editor_for_navigation_post_type' not found or invalid function name in <b>/www/doc/www.cmmj.cz/www/wp-includes/class-wp-hook.php</b> on line <b>307</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /www/doc/www.cmmj.cz/www/wp-includes/class-wp-hook.php:307) in <b>/www/doc/www.cmmj.cz/www/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1713</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /www/doc/www.cmmj.cz/www/wp-includes/class-wp-hook.php:307) in <b>/www/doc/www.cmmj.cz/www/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1713</b><br />
<br />
<b>Warning</b>:  Cannot modify header information - headers already sent by (output started at /www/doc/www.cmmj.cz/www/wp-includes/class-wp-hook.php:307) in <b>/www/doc/www.cmmj.cz/www/wp-includes/rest-api/class-wp-rest-server.php</b> on line <b>1713</b><br />
{"id":928,"date":"2022-03-01T01:39:59", ...some valid JSON here, not sure if it contains some keys or tokens so I redacted it...}
[01-Mar-2022 00:40:00 UTC] 
[01-Mar-2022 00:40:00 UTC] 
```

I can see the `$body` variable in that file contains some extra warnings, which seems to be preventing the `json_decode()` call to go through. Hope this helps. Any ideas how to fix this? What could be wrong with the target web file?

The push operation goes through and the post is visible on the target website (or at least in my case, pushing 1 post to 1 website, might be different for @vlastaw's case, pushing 1 post to multiple websites).

**Comment by dkotter** [comment]
@michalletavka Thanks for the additional information, that's super helpful. This seems to be the same issue I discovered in #844, which a fix was added in PR #845. This fix has not been released yet (targeted for a 1.7.0 release) but if you want, you can either check out that PR or since it's been merged into `develop`, you can checkout `develop` and see if that fixes things for you.

**Comment by vlastaw** [comment]
Hello, we updated both instances to develop and the issue is still present. I don't think it's related to #844

**Comment by jeffpaul** [comment]
@vlastaw did you build the develop branch?

**Comment by vlastaw** [comment]
Hi. Not used to work with git, so I just downloaded ZIP file of the develop branch and overwritten all older files in the plugin directory. So I guess yes, we are running the current Develop branch state.

**Comment by jeffpaul** [comment]
@vlastaw if you're going to download a ZIP, please use a [released version](https://github.com/10up/distributor/releases).
