### ISSUE TITLE
How does the plugin assign an author

### ISSUE THREAD

**Issue by ybalkind** [10up/distributor#856]
### Describe your question

Your documentation says 

> **Distributing Authors** - By default, distributed stories reference the original site as the "author" with a link to it. This can be altered by extending Distributor with custom code to make it sync authors.

2 questions about authors:

Questions 1) where does the remote site reference the original site as the author? I dont see this on my remote site, maybe my theme is hiding it?

Question 2) In terms of the actual author assigned to the post in the author field, am I right to say that the main site administrator of the remote site will always be assigned on the remote site regardless of who the author is on the main site? Or, if I'm wrong on this can you please explain how author is assigned on remote site exactly? 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
> Questions 1) where does the remote site reference the original site as the author? I dont see this on my remote site, maybe my theme is hiding it?

This varies a bit between Internal and External connections but both store the original site information with items that are distributed. This information is then output by using the `the_author` and `author_link` filters. There are a number of core WordPress functions that will fire this filter (like `the_author` or `get_the_author`) so whichever theme you are using will need to use one of those functions for this feature to work. Since it sounds like you don't see that, I'd suspect your theme must not be using one of those

> Question 2) In terms of the actual author assigned to the post in the author field, am I right to say that the main site administrator of the remote site will always be assigned on the remote site regardless of who the author is on the main site? Or, if I'm wrong on this can you please explain how author is assigned on remote site exactly?

So this will also vary a bit depending on if you use Internal or External connections. For Internal, we try and use the same author on both sites (assuming they exist on both sites).

For External connections, the assumption is authors won't match between sites so whichever account was used to set up the authentication for that connection, they become the user that always gets assigned as the author. This isn't necessarily the same as the administrator user, though often that will be the case.
