### ISSUE TITLE
WordPress 5.9.3 pushing does not work between sites

### ISSUE THREAD

**Issue by PaddyWhacks** [10up/distributor#870]
### Describe the bug

When pushing from 1 WP multisite to 1 regular WP site, both on 5.9.3 (WP Latest version) our post fails giving the error "Cannot identify remote post ID". Both sites have WordFence, but it is correctly setup to allow for the remote posting. 

Reverting the target back to WP 5.8.4 seems to fix the issue.

Anyone else experience this issue?

### Steps to Reproduce

Have Both sites on 5.9.3
Try distribute post from multisite to single site
It will fail
Revert target site back to 5.8.4 and it will work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
Thanks for the report @PaddyWhacks. I tried reproducing today, pushing from a WordPress multisite that is running WP 5.9.3 to another (external) WordPress multisite that is also running WP 5.9.3 and was not able to reproduce this issue.

Not sure if this helps but here's the flow on when that error will happen:
- When pushing to an external connection, we make a request to the `types` endpoint on that external connection in order to determine what the proper REST API URL is for the post type being pushed. This endpoint should be something like https://example.com/wp-json/wp/v2/types
- If that endpoint exists and returns something, we then get the proper URL from that response. For instance, if dealing with the `post` post type, it will look for `$response['post']['_links']['wp:items']['href']`.
- Assuming that returns a value, we then build up the data we want to send and than make a POST request to that endpoint. If we get a response back but that response does not contain the `id` parameter, we then output the error you're seeing: `Could not determine remote post id.`

In your testing when you get that error, do you see the actual item being created correctly on the target site? Meaning you get an error on the origin site but the item you're pushing does get sent correctly. Or do you get that error and the item doesn't get created on the external site? I'm assuming it's the latter and if so, that would suggest something is going wrong when the external site tries to create that item. Have you looked at the error logs of the external site to see if that contains any useful information?
