### ISSUE TITLE
Is there a way to undistribute a post?

### ISSUE THREAD

**Issue by bcobin** [10up/distributor#883]
### Describe your question

It looks like once a post is distributed, there's no way to undistribiute it - is that correct? Working with a bunch of events and we needed to reformat the custom fields to avoid days that crossed midnight from taking up two days on the calendar - unfortunately, already-distributed events do not reflect the changes. Absent the loss of sync, one would hope that you could undistribute, edit and redistribute - this doesn't seem to be possible either.

I've been using Drupal Domain Access for years and it's way more straightforward - any assistance greatly appreciated! I'm hoping that I don't have to delete all events and start from scratch... Yikes! Thanks for the plug-in and and any assistance!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bcobin** [comment]
After looking into tis further, perhaps this is supposed to be handled by push/pull, however, in our case (which is a multisite), unlinking the child post doesn't affect the reported status on the source. In other words, when the child is unlinked, the parent post still reports it as distributed, which is confusing, at the very least.

It also seems that updating the original post does not automatically push - so two separate operations are required: the update of the original and then the pull from the target site. If the workflow could be simplified (perhaps by means of additional settings options), we think that would be a big improvement.

Thanks again for the plug-in and for any guidance!

**Comment by jeffpaul** [comment]
@bcobin if you keep the remote posts connected, then updates on the origin post should sync to those remote posts.  If you're not seeing that happen, please confirm more details about your environment and set up.

Otherwise, and to your initial question, to clear the Distributor link so that you can re-distribute a post (via push or pull) you'll need to remove the given site from the mapping in post meta. 

_[side note: @dkotter perhaps a more straightforward approach for folks to do this might be a worthwhile feature enhancement post the current refactorings we're considering?]_
