### ISSUE TITLE
Untranslatable strings.

### ISSUE THREAD

**Issue by peterwilsoncc** [10up/distributor#918]
### Describe the bug

In a number of locations the translation strings are buggy an unable to be translated.

In most cases strings are concatenated, thereby assuming all languages follow the same format as English. `assets/js/gutenberg-syndicated-post.js` has several examples.

In other locations they assume appending the letter `s` to a word pluralizes it.

https://github.com/10up/distributor/blob/8d640629b58e6787faa2c64576d45f116d7fbed8/assets/js/gutenberg-plugin.js#L89-L93

Let's review some strings.

- [x] Ensure no sentences are made up of concatenated strings
- [x] Use correct pluralization functions
- [ ] Add contexts using `_x` as required
- [x] Ensure placeholders are proceeded by translator comments

### Steps to Reproduce

1. Translate Distributor to a non latin aphabet
2. Within the block editor, distribute article to multiple connections
3. observe the translated version of the word connections ends in the latin letter s.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kmgalanakis** [comment]
I checked all the instances of the `l10n` methods inside the plugin and:
* Didn't find any sentences made up of concatenated strings
* Verified that all the pluralized `l10n` strings are using the correct pluralization functions
* Verified (hoping I didn't miss any) that placeholders are proceeded by translator comments

What puzzles me @peterwilsoncc is how/when we decide to use `_x()` instead of `__()`. I know the difference between the two but during development (or review) how can we know if we will want to have different translations for an English string? Apart from the obvious cases where a word in English might have different meanings depending on the context, is there another reason the `_x()` should be preferred against `__()`?

Apart from that, all looks good in terms of translateable strings.

**Comment by peterwilsoncc** [comment]
> how/when we decide to use `_x()` instead of `__()`.

I don't know that there is any consistent rule for this. Generally, I think it's fine to start with `__()` and only switch if there are potential issues from using the same term, for example [words that can be both nouns and verbs](https://www.enchantedlearning.com/wordlist/nounandverb.shtml).

If nothing is grabbing your attention as needing additional context then I am happy to consider this as complete and close the issue as complete.
