### ISSUE TITLE
Re-distribute after deletion?

### ISSUE THREAD

**Issue by sjmwa** [10up/distributor#929]
### Describe your question

If I push a post and then want to remove it completely from the distributed site and start over is that possible?

I've tried unlinking...completely trashing and deleting, and also tried removing all meta from the post as described here:
https://github.com/10up/distributor/issues/883

I'm unable to re-distribute...it is still grayed out. Does something else need to be cleared from the database?

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@sjmwa if you come across this case again, I'd recommend marking the distributed post as a draft, make whatever updates you want in the origin post (updates will distribute to the other post) and then when things are ready mark the distributed post as published.  In order to fix your current issue, you'll want to make sure the meta on the origin post does not include your distributed post (which it sounds like you checked, but please double check as that'll block you from being able to re-distribute there).
