### ISSUE TITLE
Only the main superadmin user can distribute?

### ISSUE THREAD

**Issue by pdewouters** [10up/distributor#982]
### Describe your question

Distributor 1.8.0
WP 6.1.1

I have a CPT "courses" - only the initial superadmin user can distribute courses. If I switch to another user, I see "No connections available for distribution."

Any tips?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by peterwilsoncc** [comment]
Hi Paul,

Does the user you have switched to have permission to edit and read the post type `post` on the site? Looking at the registration of the connections CPT, it uses the `post` capability so it appears users need to be able to read posts in order to make use of them.

https://github.com/10up/distributor/blob/3735ccb3135a9fd21095110b4a3f7c79343272d1/includes/external-connection-cpt.php#L719-L753

I'll do some further investigation in the mean time.

**Comment by pdewouters** [comment]
I tested again and it seems to have fixed itself! I'll lose for now, if it reappears, I'll investigate further, thanks
